name: Publicar Documentação no GitBook

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/publicar-docs.yml'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Publicar no GitBook
        uses: gitbook/github-action@latest
        with:
          token: ${{ secrets.GITBOOK_TOKEN }}